version: 2.1

parameters:
  should_dig:
    type: boolean
    default: false
  dig_spot:
    type: string
    default: ''
  additional_remote:
    type: string
    default: ''
  base_branch:
    type: string
    default: ''

jobs:
  build:
    docker:
      - image: cimg/node:16.15
    working_directory: ~/repo
    steps:
      - checkout

  dig:
    docker:
      - image: cimg/node:16.15
    working_directory: ~/electron
    steps:
      - run: git clone https://github.com/electron/electron.git .
      - run: mkdir -p artifacts
      - run: git remote add fork << pipeline.parameters.additional_remote >> && git fetch fork
      - run: git checkout << pipeline.parameters.dig_spot >>
      - run: git merge-base origin/<< pipeline.parameters.base_branch >> HEAD > .dig-old
      - run:
          command: |
            rm -rf node_modules
            yarn install --frozen-lockfile
      - run: echo "#!/usr/bin/env node\nglobal.x=1" > node_modules/typescript/bin/tsc
      - run:
          command: |
            if [ -f "node_modules/.bin/electron-docs-parser" ]; then
              node node_modules/.bin/electron-docs-parser --dir=./ --outDir=./
            else
              node node_modules/.bin/electron-docs-linter docs --outfile=electron-api.json --version=0.0.0-archaeologist.0
            fi
      - run:
          command: |
            if [ -f "node_modules/.bin/electron-docs-parser" ]; then
              node node_modules/.bin/electron-typescript-definitions --api=electron-api.json --outDir=artifacts
              mv artifacts/electron.d.ts artifacts/electron.new.d.ts
            else
              node node_modules/.bin/electron-typescript-definitions docs --in=electron-api.json --out=artifacts/electron.new.d.ts
            fi
      - run: git checkout .
      - run: git checkout $(cat .dig-old)
      - run:
          command: |
            rm -rf node_modules
            yarn install --frozen-lockfile
      - run: echo "#!/usr/bin/env node\nglobal.x=1" > node_modules/typescript/bin/tsc
      - run:
          command: |
            if [ -f "node_modules/.bin/electron-docs-parser" ]; then
              node node_modules/.bin/electron-docs-parser --dir=./ --outDir=./
            else
              node node_modules/.bin/electron-docs-linter docs --outfile=electron-api.json --version=0.0.0-archaeologist.0
            fi
      - run:
          command: |
            if [ -f "node_modules/.bin/electron-docs-parser" ]; then
              node node_modules/.bin/electron-typescript-definitions --api=electron-api.json --outDir=artifacts
              mv artifacts/electron.d.ts artifacts/electron.old.d.ts
            else
              node node_modules/.bin/electron-typescript-definitions docs --in=electron-api.json --out=artifacts/electron.old.d.ts
            fi
      - run: mv .dig-old artifacts
      - store_artifacts:
          path: artifacts

workflows:
  version: 2
  build:
    when:
      condition:
        not: << pipeline.parameters.should_dig >>
    jobs:
      - build
  
  dig:
    when:
      condition: << pipeline.parameters.should_dig >>
    jobs:
      - dig